### ISSUE TITLE
config.yml ('This file could not be opened')

### ISSUE THREAD

**Issue by izchieve** [bjamesv/pyAndChargeLimit#1]
So I've been looking for apps to limit the charging to only 80% to stop battery deterioration, and fortunately found this. I've done all the necessary requirements for the setup, but I couldn't run the pyAndChargeLimit to use it. I cannot open the config.yml for this directory: Explorer > scripts > config.yml .

**Comment by bjamesv** [comment]
It looks like the version of QPython I use has the same problem (Unable to edit .yml files / `This file could not be opened`).

I've retyped the README Usage to clarify that you'll need to edit `config.yml` first, before you copy it to your device.

**Comment by bjamesv** [comment]
If editing `config.yml` on-device is absolutely necessary, we can work around QPython app limitation by:
- Swipe left on Explorer > scripts > config.yml
- Tap the center 🖉 'Rename' icon, rename to `config.yml.txt`, and tap OK
- Tap again to edit
- When done, swipe left again and rename back to `config.yml`
